name: discover_printers
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.5 <3.0.0"

dependencies:
#  charset_converter: ^1.0.3
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  esc_pos_printer: ^3.1.6
  esc_pos_utils: ^0.3.6
#  image: ^2.1.4
#  intl: ^0.16.1
#  path_provider: ^1.6.5
  ping_discover_network: ^0.2.0
#  qr_flutter: ^3.2.0
  wifi: ^0.1.5
  bluetooth_thermal_printer: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true